# Generated by Django 6.1.1 on 2026-09-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(help_text='Fecha del evento (YYYY-MM-DD)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(help_text='Día en que se hará la gestión (YYYY-MM-DD)')),
                ('hora', models.TimeField(help_text='Hora de la gestión (HH:MM)')),
                ('horas', models.DecimalField(decimal_places=2, help_text='Horas estimadas que tomará (entre 0.5 y 8)', max_digits=4)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('hecho', 'Hecho'), ('pospuesto', 'Pospuesto')], default='pendiente', max_length=20)),
                ('nota', models.TextField(blank=True, default='')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='events.evento')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
