# Generated by Django 6.1.1 on 2026-10-09 13:48

import django.core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_preferenciasusuario_evento_limite_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='limite_horas',
        ),
        migrations.AlterField(
            model_name='preferenciasusuario',
            name='limite_horas',
            field=models.DecimalField(decimal_places=2, default=6, help_text='Límite de horas de trabajo al día (entre 1 y 12, por defecto 6)', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12), events.models.validar_paso_media_hora]),
        ),
    ]
